### ISSUE TITLE
Unable to copy/paste card info.

### ISSUE THREAD

**Issue by mindtheworld** [Nets-eCom/Nets-Easy-iOS-SDK#20]
Our integration is based on ReactNative, is there a way to enable copy/paste functionality in payment window? 

![image](https://user-images.githubusercontent.com/34175635/155182038-71127937-b9cb-4448-8e15-2933954eff78.png)

Also password manager is not supported under IOS. (but works fine on Android phone)

**Comment by Nets-in-app** [comment]
Hi @mindtheworld ,

The copy/paste operation is indeed not supported in MiA iOS SDK at the moment, due to the security vulnerability. In short, the copy paste operation for the sensitive card data in plaintext can lead to other applications access to the obtain the card data from the mobile environment. For this reason, our SDK mitigates the risk to protect the sensitive data by disabling the copy paste operation. In the long term, we will evaluate the option to enable the secure copy/paste provided from the mobile platforms to enable the copy/paste action for the easier card entry.
